### ISSUE TITLE
Force the app to speak HTTPS

### ISSUE THREAD

**Issue by sdavids13** [sdavids13/checkers#1]
Add the tomcat configuration to speak https and hook it into the maven plugin. Something along the lines of: http://stackoverflow.com/questions/11633486/ssl-configuration-on-maven-tomcat-plugin

**Comment by j13elliott** [comment]
Got it working in local env with hard-coded keystore path.  Will check-in updated pom.xml and certificate directory with keystore in a bit.

**Comment by sdavids13** [comment]
Cool, looks good. Just updated the web.xml to force HTTPS when a client connects via HTTP.
