### ISSUE TITLE
Validate a secure password is entered

### ISSUE THREAD

**Issue by sdavids13** [sdavids13/checkers#9]
When a user creates a new account, the password should be validated to be "secure" - something along the lines of 6-14 characters with a mix of characters and numbers/special chars.

Right now the form is being bound to the User bean which validates the username, unfortunately the password isn't able to validated because it is eventually overridden with the salted+hashed value. Since JPA performs the bean validation at persistence time it won't validate with the updated hashed value (way too large). Thus we can setup a Data Transfer Object which is used to bind to the form and validate username/password within that object, then build a new User object from those values.

...checkers.dto.UserDTO seems reasonable...

Another alternative is to perform the regex validation in the controller method.

**Comment by j13elliott** [comment]
clicked close button accidently
